export enum StreamCategoryEnum {
  MUSIC = 'music',
  GAMING = 'gaming',
  SPORTS = 'sports',
  NEWS_AND_POLITICS = 'news_and_politics',
  EDUCATION = 'education',
  ENTERTAINMENT = 'entertainment',
  COMEDY = 'comedy',
  HOWTO_AND_STYLE = 'howto_and_style',
  SCIENCE_AND_TECHNOLOGY = 'science_and_technology',
  TRAVEL_AND_EVENTS = 'travel_and_events',
  PEOPLE_AND_BLOGS = 'people_and_blogs',
  FASHION = 'fashion',
  PETS_AND_ANIMALS = 'pets_and_animals',
  AUTOS_AND_VEHICLES = 'autos_and_vehicles',
  FILM_AND_ANIMATION = 'film_and_animation',
  NONPROFITS_AND_ACTIVISM = 'nonprofits_and_activism',
  OTHER = 'other',
}